// import type { ServerLocation } from "./types"

// export const EXCHANGES: ServerLocation[] = [
//   {
//     id: "binance",
//     name: "Binance",
//     provider: "Exchange",
//     region: "Tokyo",
//     location: { lat: 35.6762, lng: 139.6503 },
//     status: "operational",
//   },
//   {
//     id: "deribit",
//     name: "Deribit",
//     provider: "Exchange",
//     region: "London",
//     location: { lat: 51.5074, lng: -0.1278 },
//     status: "operational",
//   },
//   {
//     id: "okx",
//     name: "OKX",
//     provider: "Exchange",
//     region: "Hong Kong",
//     location: { lat: 22.3193, lng: 114.1694 },
//     status: "operational",
//   },
//   {
//     id: "coinbase",
//     name: "Coinbase",
//     provider: "Exchange",
//     region: "San Francisco",
//     location: { lat: 37.7749, lng: -122.4194 },
//     status: "operational",
//   },
// ]

// export const CLOUD_REGIONS: ServerLocation[] = [
//   {
//     id: "aws-use1",
//     name: "AWS us-east-1",
//     provider: "AWS",
//     region: "N. Virginia",
//     location: { lat: 38.0339, lng: -78.5079 },
//     status: "operational",
//   },
//   {
//     id: "aws-apne1",
//     name: "AWS ap-northeast-1",
//     provider: "AWS",
//     region: "Tokyo",
//     location: { lat: 35.6895, lng: 139.6917 },
//     status: "operational",
//   },
//   {
//     id: "gcp-euw2",
//     name: "GCP europe-west2",
//     provider: "GCP",
//     region: "London",
//     location: { lat: 51.5072, lng: -0.1276 },
//     status: "operational",
//   },
//   {
//     id: "azure-eas",
//     name: "Azure East Asia",
//     provider: "Azure",
//     region: "Hong Kong",
//     location: { lat: 22.2855, lng: 114.1577 },
//     status: "operational",
//   },
//   {
//     id: "gcp-use4",
//     name: "GCP us-east4",
//     provider: "GCP",
//     region: "N. Virginia",
//     location: { lat: 39.0438, lng: -77.4874 },
//     status: "operational",
//   },
//   {
//     id: "aws-euw1",
//     name: "AWS eu-west-1",
//     provider: "AWS",
//     region: "Ireland",
//     location: { lat: 53.3498, lng: -6.2603 },
//     status: "operational",
//   },
// ]

// export const ALL_LOCATIONS = [...EXCHANGES, ...CLOUD_REGIONS]
import type { ServerLocation } from "./types"

/* ===========================
   Exchange POP Locations
   =========================== */

export const EXCHANGES: ServerLocation[] = [
  // Binance clusters
  {
    id: "binance-tokyo",
    name: "Binance - Tokyo",
    provider: "Exchange",
    region: "Tokyo",
    location: { lat: 35.6762, lng: 139.6503 },
    status: "operational",
  },
  {
    id: "binance-london",
    name: "Binance - London",
    provider: "Exchange",
    region: "London",
    location: { lat: 51.5074, lng: -0.1278 },
    status: "operational",
  },
  {
    id: "binance-newyork",
    name: "Binance - New York",
    provider: "Exchange",
    region: "New York",
    location: { lat: 40.7128, lng: -74.0060 },
    status: "operational",
  },
  {
    id: "binance-singapore",
    name: "Binance - Singapore",
    provider: "Exchange",
    region: "Singapore",
    location: { lat: 1.3521, lng: 103.8198 },
    status: "operational",
  },
  {
    id: "binance-paris",
    name: "Binance - Paris",
    provider: "Exchange",
    region: "Paris",
    location: { lat: 48.8566, lng: 2.3522 },
    status: "operational",
  },

  // Coinbase / Kraken / Bitfinex etc.
  {
    id: "coinbase-sf",
    name: "Coinbase - San Francisco",
    provider: "Exchange",
    region: "San Francisco",
    location: { lat: 37.7749, lng: -122.4194 },
    status: "operational",
  },
  {
    id: "coinbase-frankfurt",
    name: "Coinbase - Frankfurt",
    provider: "Exchange",
    region: "Frankfurt",
    location: { lat: 50.1109, lng: 8.6821 },
    status: "operational",
  },
  {
    id: "kraken-london",
    name: "Kraken - London",
    provider: "Exchange",
    region: "London",
    location: { lat: 51.5074, lng: -0.1278 },
    status: "operational",
  },
  {
    id: "kraken-newyork",
    name: "Kraken - New York",
    provider: "Exchange",
    region: "New York",
    location: { lat: 40.7128, lng: -74.0060 },
    status: "operational",
  },

  // Bybit / OKX / Huobi etc. in Asia + Middle East
  {
    id: "bybit-singapore",
    name: "Bybit - Singapore",
    provider: "Exchange",
    region: "Singapore",
    location: { lat: 1.3521, lng: 103.8198 },
    status: "operational",
  },
  {
    id: "bybit-dubai",
    name: "Bybit - Dubai",
    provider: "Exchange",
    region: "Dubai",
    location: { lat: 25.2048, lng: 55.2708 },
    status: "operational",
  },
  {
    id: "okx-hongkong",
    name: "OKX - Hong Kong",
    provider: "Exchange",
    region: "Hong Kong",
    location: { lat: 22.3193, lng: 114.1694 },
    status: "operational",
  },
  {
    id: "okx-singapore",
    name: "OKX - Singapore",
    provider: "Exchange",
    region: "Singapore",
    location: { lat: 1.3521, lng: 103.8198 },
    status: "operational",
  },
  {
    id: "huobi-singapore",
    name: "Huobi - Singapore",
    provider: "Exchange",
    region: "Singapore",
    location: { lat: 1.3521, lng: 103.8198 },
    status: "operational",
  },

  // Bitfinex / Bitstamp / KuCoin etc. in Europe
  {
    id: "bitfinex-london",
    name: "Bitfinex - London",
    provider: "Exchange",
    region: "London",
    location: { lat: 51.5074, lng: -0.1278 },
    status: "operational",
  },
  {
    id: "bitfinex-zurich",
    name: "Bitfinex - Zurich",
    provider: "Exchange",
    region: "Zurich",
    location: { lat: 47.3769, lng: 8.5417 },
    status: "operational",
  },
  {
    id: "bitstamp-london",
    name: "Bitstamp - London",
    provider: "Exchange",
    region: "London",
    location: { lat: 51.5074, lng: -0.1278 },
    status: "operational",
  },
  {
    id: "kucoin-amsterdam",
    name: "KuCoin - Amsterdam",
    provider: "Exchange",
    region: "Amsterdam",
    location: { lat: 52.3676, lng: 4.9041 },
    status: "operational",
  },
  {
    id: "kucoin-singapore",
    name: "KuCoin - Singapore",
    provider: "Exchange",
    region: "Singapore",
    location: { lat: 1.3521, lng: 103.8198 },
    status: "operational",
  },

  // Deribit, Gate.io, Poloniex, etc.
  {
    id: "deribit-amsterdam",
    name: "Deribit - Amsterdam",
    provider: "Exchange",
    region: "Amsterdam",
    location: { lat: 52.3676, lng: 4.9041 },
    status: "operational",
  },
  {
    id: "gateio-chicago",
    name: "Gate.io - Chicago",
    provider: "Exchange",
    region: "Chicago",
    location: { lat: 41.8781, lng: -87.6298 },
    status: "operational",
  },
  {
    id: "poloniex-newyork",
    name: "Poloniex - New York",
    provider: "Exchange",
    region: "New York",
    location: { lat: 40.7128, lng: -74.0060 },
    status: "operational",
  },

  // Korean exchanges
  {
    id: "upbit-seoul",
    name: "Upbit - Seoul",
    provider: "Exchange",
    region: "Seoul",
    location: { lat: 37.5665, lng: 126.9780 },
    status: "operational",
  },
  {
    id: "bithumb-seoul",
    name: "Bithumb - Seoul",
    provider: "Exchange",
    region: "Seoul",
    location: { lat: 37.5665, lng: 126.9780 },
    status: "operational",
  },
  {
    id: "bitflyer-tokyo",
    name: "bitFlyer - Tokyo",
    provider: "Exchange",
    region: "Tokyo",
    location: { lat: 35.6895, lng: 139.6917 },
    status: "operational",
  },

  // LATAM exchanges
  {
    id: "bitso-mexico",
    name: "Bitso - Mexico City",
    provider: "Exchange",
    region: "Mexico City",
    location: { lat: 19.4326, lng: -99.1332 },
    status: "operational",
  },
  {
    id: "mercadobitcoin-saopaulo",
    name: "Mercado Bitcoin - Sao Paulo",
    provider: "Exchange",
    region: "Sao Paulo",
    location: { lat: -23.5505, lng: -46.6333 },
    status: "operational",
  },

  // Africa / Middle East
  {
    id: "luno-johannesburg",
    name: "Luno - Johannesburg",
    provider: "Exchange",
    region: "Johannesburg",
    location: { lat: -26.2041, lng: 28.0473 },
    status: "operational",
  },
  {
    id: "rain-dubai",
    name: "Rain - Dubai",
    provider: "Exchange",
    region: "Dubai",
    location: { lat: 25.2048, lng: 55.2708 },
    status: "operational",
  },

  // India & South Asia
  {
    id: "wazirx-mumbai",
    name: "WazirX - Mumbai",
    provider: "Exchange",
    region: "Mumbai",
    location: { lat: 19.0760, lng: 72.8777 },
    status: "operational",
  },
  {
    id: "coindcx-mumbai",
    name: "CoinDCX - Mumbai",
    provider: "Exchange",
    region: "Mumbai",
    location: { lat: 19.0760, lng: 72.8777 },
    status: "operational",
  },
  {
    id: "coinswitch-bangalore",
    name: "CoinSwitch - Bengaluru",
    provider: "Exchange",
    region: "Bengaluru",
    location: { lat: 12.9716, lng: 77.5946 },
    status: "operational",
  },
  {
    id: "zebpay-mumbai",
    name: "ZebPay - Mumbai",
    provider: "Exchange",
    region: "Mumbai",
    location: { lat: 19.0760, lng: 72.8777 },
    status: "operational",
  },

  // Australia / APAC
  {
    id: "btcmarkets-sydney",
    name: "BTC Markets - Sydney",
    provider: "Exchange",
    region: "Sydney",
    location: { lat: -33.8688, lng: 151.2093 },
    status: "operational",
  },
  {
    id: "coinspot-melbourne",
    name: "CoinSpot - Melbourne",
    provider: "Exchange",
    region: "Melbourne",
    location: { lat: -37.8136, lng: 144.9631 },
    status: "operational",
  },
  {
    id: "indodax-jakarta",
    name: "Indodax - Jakarta",
    provider: "Exchange",
    region: "Jakarta",
    location: { lat: -6.2088, lng: 106.8456 },
    status: "operational",
  },

  // US-based (Gemini, Bittrex, OKCoin, Crypto.com)
  {
    id: "gemini-newyork",
    name: "Gemini - New York",
    provider: "Exchange",
    region: "New York",
    location: { lat: 40.7128, lng: -74.0060 },
    status: "operational",
  },
  {
    id: "bittrex-seattle",
    name: "Bittrex - Seattle",
    provider: "Exchange",
    region: "Seattle",
    location: { lat: 47.6062, lng: -122.3321 },
    status: "operational",
  },
  {
    id: "okcoin-sanfrancisco",
    name: "OKCoin - San Francisco",
    provider: "Exchange",
    region: "San Francisco",
    location: { lat: 37.7749, lng: -122.4194 },
    status: "operational",
  },
  {
    id: "cryptocom-hongkong",
    name: "Crypto.com - Hong Kong",
    provider: "Exchange",
    region: "Hong Kong",
    location: { lat: 22.3193, lng: 114.1694 },
    status: "operational",
  },
  {
    id: "cryptocom-london",
    name: "Crypto.com - London",
    provider: "Exchange",
    region: "London",
    location: { lat: 51.5074, lng: -0.1278 },
    status: "operational",
  },

  // Japan / extra
  {
    id: "coincheck-tokyo",
    name: "Coincheck - Tokyo",
    provider: "Exchange",
    region: "Tokyo",
    location: { lat: 35.6895, lng: 139.6917 },
    status: "operational",
  },
]

/* ===========================
   Cloud Regions (AWS / GCP / Azure)
   =========================== */

export const CLOUD_REGIONS: ServerLocation[] = [
  /* -------- AWS (17 regions) -------- */
  {
    id: "aws-us-east-1",
    name: "AWS us-east-1 (N. Virginia)",
    provider: "AWS",
    region: "us-east-1",
    location: { lat: 38.0339, lng: -78.5079 },
    status: "operational",
  },
  {
    id: "aws-us-east-2",
    name: "AWS us-east-2 (Ohio)",
    provider: "AWS",
    region: "us-east-2",
    location: { lat: 39.9612, lng: -82.9988 },
    status: "operational",
  },
  {
    id: "aws-us-west-1",
    name: "AWS us-west-1 (N. California)",
    provider: "AWS",
    region: "us-west-1",
    location: { lat: 37.7749, lng: -122.4194 },
    status: "operational",
  },
  {
    id: "aws-us-west-2",
    name: "AWS us-west-2 (Oregon)",
    provider: "AWS",
    region: "us-west-2",
    location: { lat: 45.5234, lng: -122.6762 },
    status: "operational",
  },
  {
    id: "aws-ca-central-1",
    name: "AWS ca-central-1 (Montreal)",
    provider: "AWS",
    region: "ca-central-1",
    location: { lat: 45.5017, lng: -73.5673 },
    status: "operational",
  },
  {
    id: "aws-eu-west-1",
    name: "AWS eu-west-1 (Ireland)",
    provider: "AWS",
    region: "eu-west-1",
    location: { lat: 53.3498, lng: -6.2603 },
    status: "operational",
  },
  {
    id: "aws-eu-west-2",
    name: "AWS eu-west-2 (London)",
    provider: "AWS",
    region: "eu-west-2",
    location: { lat: 51.5074, lng: -0.1278 },
    status: "operational",
  },
  {
    id: "aws-eu-west-3",
    name: "AWS eu-west-3 (Paris)",
    provider: "AWS",
    region: "eu-west-3",
    location: { lat: 48.8566, lng: 2.3522 },
    status: "operational",
  },
  {
    id: "aws-eu-central-1",
    name: "AWS eu-central-1 (Frankfurt)",
    provider: "AWS",
    region: "eu-central-1",
    location: { lat: 50.1109, lng: 8.6821 },
    status: "operational",
  },
  {
    id: "aws-eu-north-1",
    name: "AWS eu-north-1 (Stockholm)",
    provider: "AWS",
    region: "eu-north-1",
    location: { lat: 59.3293, lng: 18.0686 },
    status: "operational",
  },
  {
    id: "aws-ap-northeast-1",
    name: "AWS ap-northeast-1 (Tokyo)",
    provider: "AWS",
    region: "ap-northeast-1",
    location: { lat: 35.6895, lng: 139.6917 },
    status: "operational",
  },
  {
    id: "aws-ap-northeast-2",
    name: "AWS ap-northeast-2 (Seoul)",
    provider: "AWS",
    region: "ap-northeast-2",
    location: { lat: 37.5665, lng: 126.9780 },
    status: "operational",
  },
  {
    id: "aws-ap-northeast-3",
    name: "AWS ap-northeast-3 (Osaka)",
    provider: "AWS",
    region: "ap-northeast-3",
    location: { lat: 34.6937, lng: 135.5023 },
    status: "operational",
  },
  {
    id: "aws-ap-southeast-1",
    name: "AWS ap-southeast-1 (Singapore)",
    provider: "AWS",
    region: "ap-southeast-1",
    location: { lat: 1.3521, lng: 103.8198 },
    status: "operational",
  },
  {
    id: "aws-ap-southeast-2",
    name: "AWS ap-southeast-2 (Sydney)",
    provider: "AWS",
    region: "ap-southeast-2",
    location: { lat: -33.8688, lng: 151.2093 },
    status: "operational",
  },
  {
    id: "aws-ap-south-1",
    name: "AWS ap-south-1 (Mumbai)",
    provider: "AWS",
    region: "ap-south-1",
    location: { lat: 19.0760, lng: 72.8777 },
    status: "operational",
  },
  {
    id: "aws-sa-east-1",
    name: "AWS sa-east-1 (São Paulo)",
    provider: "AWS",
    region: "sa-east-1",
    location: { lat: -23.5505, lng: -46.6333 },
    status: "operational",
  },

  /* -------- GCP (13 regions) -------- */
  {
    id: "gcp-us-central1",
    name: "GCP us-central1 (Iowa)",
    provider: "GCP",
    region: "us-central1",
    location: { lat: 41.2565, lng: -95.9345 },
    status: "operational",
  },
  {
    id: "gcp-us-east1",
    name: "GCP us-east1 (S. Carolina)",
    provider: "GCP",
    region: "us-east1",
    location: { lat: 33.8361, lng: -81.1637 },
    status: "operational",
  },
  {
    id: "gcp-us-east4",
    name: "GCP us-east4 (N. Virginia)",
    provider: "GCP",
    region: "us-east4",
    location: { lat: 39.0438, lng: -77.4874 },
    status: "operational",
  },
  {
    id: "gcp-us-west1",
    name: "GCP us-west1 (Oregon)",
    provider: "GCP",
    region: "us-west1",
    location: { lat: 45.5234, lng: -122.6762 },
    status: "operational",
  },
  {
    id: "gcp-us-west2",
    name: "GCP us-west2 (Los Angeles)",
    provider: "GCP",
    region: "us-west2",
    location: { lat: 34.0522, lng: -118.2437 },
    status: "operational",
  },
  {
    id: "gcp-northamerica-northeast1",
    name: "GCP northamerica-northeast1 (Montreal)",
    provider: "GCP",
    region: "northamerica-northeast1",
    location: { lat: 45.5017, lng: -73.5673 },
    status: "operational",
  },
  {
    id: "gcp-europe-west1",
    name: "GCP europe-west1 (Belgium)",
    provider: "GCP",
    region: "europe-west1",
    location: { lat: 50.8503, lng: 4.3517 },
    status: "operational",
  },
  {
    id: "gcp-europe-west2",
    name: "GCP europe-west2 (London)",
    provider: "GCP",
    region: "europe-west2",
    location: { lat: 51.5074, lng: -0.1278 },
    status: "operational",
  },
  {
    id: "gcp-europe-west3",
    name: "GCP europe-west3 (Frankfurt)",
    provider: "GCP",
    region: "europe-west3",
    location: { lat: 50.1109, lng: 8.6821 },
    status: "operational",
  },
  {
    id: "gcp-asia-east1",
    name: "GCP asia-east1 (Taiwan)",
    provider: "GCP",
    region: "asia-east1",
    location: { lat: 25.0330, lng: 121.5654 },
    status: "operational",
  },
  {
    id: "gcp-asia-northeast1",
    name: "GCP asia-northeast1 (Tokyo)",
    provider: "GCP",
    region: "asia-northeast1",
    location: { lat: 35.6895, lng: 139.6917 },
    status: "operational",
  },
  {
    id: "gcp-asia-south1",
    name: "GCP asia-south1 (Mumbai)",
    provider: "GCP",
    region: "asia-south1",
    location: { lat: 19.0760, lng: 72.8777 },
    status: "operational",
  },
  {
    id: "gcp-australia-southeast1",
    name: "GCP australia-southeast1 (Sydney)",
    provider: "GCP",
    region: "australia-southeast1",
    location: { lat: -33.8688, lng: 151.2093 },
    status: "operational",
  },

  /* -------- Azure (15 regions) -------- */
  {
    id: "azure-eastus",
    name: "Azure East US",
    provider: "Azure",
    region: "eastus",
    location: { lat: 37.3719, lng: -79.8164 },
    status: "operational",
  },
  {
    id: "azure-eastus2",
    name: "Azure East US 2",
    provider: "Azure",
    region: "eastus2",
    location: { lat: 36.6681, lng: -78.3889 },
    status: "operational",
  },
  {
    id: "azure-centralus",
    name: "Azure Central US",
    provider: "Azure",
    region: "centralus",
    location: { lat: 41.5908, lng: -93.6208 },
    status: "operational",
  },
  {
    id: "azure-westus",
    name: "Azure West US",
    provider: "Azure",
    region: "westus",
    location: { lat: 37.3382, lng: -121.8863 },
    status: "operational",
  },
  {
    id: "azure-westus2",
    name: "Azure West US 2",
    provider: "Azure",
    region: "westus2",
    location: { lat: 47.2330, lng: -119.8525 },
    status: "operational",
  },
  {
    id: "azure-northcentralus",
    name: "Azure North Central US",
    provider: "Azure",
    region: "northcentralus",
    location: { lat: 41.8781, lng: -87.6298 },
    status: "operational",
  },
  {
    id: "azure-southcentralus",
    name: "Azure South Central US",
    provider: "Azure",
    region: "southcentralus",
    location: { lat: 29.4241, lng: -98.4936 },
    status: "operational",
  },
  {
    id: "azure-canadacentral",
    name: "Azure Canada Central",
    provider: "Azure",
    region: "canadacentral",
    location: { lat: 43.6532, lng: -79.3832 },
    status: "operational",
  },
  {
    id: "azure-brazilsouth",
    name: "Azure Brazil South",
    provider: "Azure",
    region: "brazilsouth",
    location: { lat: -23.5505, lng: -46.6333 },
    status: "operational",
  },
  {
    id: "azure-westeurope",
    name: "Azure West Europe",
    provider: "Azure",
    region: "westeurope",
    location: { lat: 52.3676, lng: 4.9041 },
    status: "operational",
  },
  {
    id: "azure-northeurope",
    name: "Azure North Europe",
    provider: "Azure",
    region: "northeurope",
    location: { lat: 53.3478, lng: -6.2597 },
    status: "operational",
  },
  {
    id: "azure-uksouth",
    name: "Azure UK South",
    provider: "Azure",
    region: "uksouth",
    location: { lat: 51.5074, lng: -0.1278 },
    status: "operational",
  },
  {
    id: "azure-francecentral",
    name: "Azure France Central",
    provider: "Azure",
    region: "francecentral",
    location: { lat: 48.8566, lng: 2.3522 },
    status: "operational",
  },
  {
    id: "azure-eastasia",
    name: "Azure East Asia",
    provider: "Azure",
    region: "eastasia",
    location: { lat: 22.3193, lng: 114.1694 },
    status: "operational",
  },
  {
    id: "azure-southeastasia",
    name: "Azure Southeast Asia",
    provider: "Azure",
    region: "southeastasia",
    location: { lat: 1.3521, lng: 103.8198 },
    status: "operational",
  },
]

/* ===========================
   Combined Locations
   =========================== */

export const ALL_LOCATIONS: ServerLocation[] = [...EXCHANGES, ...CLOUD_REGIONS]
